-- =============================================================================
-- V1 — Core schema for the E-Commerce Order Management System.
--
-- This single migration owns the full schema and grows one vertical slice at a
-- time as the system is built (auth → catalog/inventory → cart/pricing →
-- order/payment → fulfillment → returns). Seed data lives in V2__seed.sql.
--
-- DDL is written to run unchanged on both PostgreSQL 16 (app) and H2 in
-- PostgreSQL-compatibility mode (tests): identity columns, NUMERIC(19,2) money,
-- TIMESTAMP, and TEXT only — no engine-specific types.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Users & authentication
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(120) NOT NULL,
    role          VARCHAR(32)  NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'CUSTOMER', 'WAREHOUSE_STAFF'))
);

