-- =============================================================================
-- V1 — Core schema for the E-Commerce Order Management System.
--
-- This single migration owns the full schema and grows one vertical slice at a
-- time as the system is built (auth → catalog/inventory → cart/pricing →
-- order/payment → fulfillment → returns). Seed data lives in V2__seed.sql.
--
-- DDL is written to run unchanged on both PostgreSQL 16 (app) and H2 in
-- PostgreSQL-compatibility mode (tests): identity columns, NUMERIC(19,2) money,
-- TIMESTAMP, and TEXT only — no engine-specific types.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Users & authentication
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(120) NOT NULL,
    role          VARCHAR(32)  NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'CUSTOMER', 'WAREHOUSE_STAFF'))
);

-- -----------------------------------------------------------------------------
-- Catalog: categories (self-referencing hierarchy) and products
-- -----------------------------------------------------------------------------
CREATE TABLE categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version    BIGINT       NOT NULL DEFAULT 0,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    name       VARCHAR(120) NOT NULL,
    parent_id  BIGINT,
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
);

CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      BIGINT        NOT NULL DEFAULT 0,
    created_at   TIMESTAMP     NOT NULL,
    updated_at   TIMESTAMP     NOT NULL,
    sku          VARCHAR(64)   NOT NULL,
    name         VARCHAR(200)  NOT NULL,
    description  TEXT,
    base_price   NUMERIC(19,2) NOT NULL,
    tax_category VARCHAR(32)   NOT NULL DEFAULT 'STANDARD',
    active       BOOLEAN       NOT NULL DEFAULT TRUE,
    category_id  BIGINT,
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_products_base_price CHECK (base_price >= 0)
);

CREATE INDEX idx_products_category ON products (category_id);

-- -----------------------------------------------------------------------------
-- Inventory: warehouses and per-product stock levels
-- -----------------------------------------------------------------------------
CREATE TABLE warehouses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version    BIGINT       NOT NULL DEFAULT 0,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    code       VARCHAR(32)  NOT NULL,
    name       VARCHAR(120) NOT NULL,
    region     VARCHAR(64),
    priority   INTEGER      NOT NULL DEFAULT 100,
    CONSTRAINT uq_warehouses_code UNIQUE (code)
);

CREATE TABLE stock_levels (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           BIGINT  NOT NULL DEFAULT 0,
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
    product_id        BIGINT  NOT NULL,
    warehouse_id      BIGINT  NOT NULL,
    quantity_on_hand  INTEGER NOT NULL DEFAULT 0,
    quantity_reserved INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_stock_product   FOREIGN KEY (product_id)   REFERENCES products (id),
    CONSTRAINT fk_stock_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT uq_stock_product_warehouse UNIQUE (product_id, warehouse_id),
    CONSTRAINT ck_stock_on_hand  CHECK (quantity_on_hand >= 0),
    CONSTRAINT ck_stock_reserved CHECK (quantity_reserved >= 0 AND quantity_reserved <= quantity_on_hand)
);

-- -----------------------------------------------------------------------------
-- Pricing: tax rates and coupons
-- -----------------------------------------------------------------------------
CREATE TABLE tax_rates (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      BIGINT       NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    tax_category VARCHAR(32)  NOT NULL,
    region       VARCHAR(64)  NOT NULL,
    rate_percent NUMERIC(6,3) NOT NULL,
    CONSTRAINT uq_tax_category_region UNIQUE (tax_category, region),
    CONSTRAINT ck_tax_rate_percent CHECK (rate_percent >= 0)
);

CREATE TABLE coupons (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          BIGINT        NOT NULL DEFAULT 0,
    created_at       TIMESTAMP     NOT NULL,
    updated_at       TIMESTAMP     NOT NULL,
    code             VARCHAR(64)   NOT NULL,
    type             VARCHAR(16)   NOT NULL,
    discount_value   NUMERIC(19,2) NOT NULL,
    min_order_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    valid_from       TIMESTAMP,
    valid_to         TIMESTAMP,
    max_redemptions  INTEGER,
    times_redeemed   INTEGER       NOT NULL DEFAULT 0,
    active           BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_coupons_code UNIQUE (code),
    CONSTRAINT ck_coupons_type CHECK (type IN ('PERCENT', 'FIXED')),
    CONSTRAINT ck_coupons_value CHECK (discount_value >= 0),
    CONSTRAINT ck_coupons_redeemed CHECK (times_redeemed >= 0)
);

-- -----------------------------------------------------------------------------
-- Cart: one active cart per customer (enforced in the service layer)
-- -----------------------------------------------------------------------------
CREATE TABLE carts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    created_at  TIMESTAMP   NOT NULL,
    updated_at  TIMESTAMP   NOT NULL,
    customer_id BIGINT      NOT NULL,
    status      VARCHAR(20) NOT NULL,
    coupon_code VARCHAR(64),
    CONSTRAINT fk_carts_customer FOREIGN KEY (customer_id) REFERENCES users (id),
    CONSTRAINT ck_carts_status CHECK (status IN ('ACTIVE', 'CHECKED_OUT', 'ABANDONED'))
);

CREATE INDEX idx_carts_customer_status ON carts (customer_id, status);

CREATE TABLE cart_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             BIGINT        NOT NULL DEFAULT 0,
    created_at          TIMESTAMP     NOT NULL,
    updated_at          TIMESTAMP     NOT NULL,
    cart_id             BIGINT        NOT NULL,
    product_id          BIGINT        NOT NULL,
    quantity            INTEGER       NOT NULL,
    unit_price_snapshot NUMERIC(19,2) NOT NULL,
    CONSTRAINT fk_cart_items_cart    FOREIGN KEY (cart_id)    REFERENCES carts (id),
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_cart_items_cart_product UNIQUE (cart_id, product_id),
    CONSTRAINT ck_cart_items_quantity CHECK (quantity > 0)
);

